version: '3.8'

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    expose:
      - "27017"

  redis:
    image: redis:alpine
    depends_on:
      - mongo

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - nginx

volumes:
  mongodb_data: